// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Home: typeof import('./components/Home.vue')['default']
    Mint: typeof import('./components/Mint.vue')['default']
    Share: typeof import('./components/Share.vue')['default']
    Stake: typeof import('./components/Stake.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
  }
}

export {}
